/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'robson' at '5/1/16 9:57 PM' with Gradle 2.13
 *
 * @author robson, @date 5/1/16 9:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
